### PR TITLE
fix: remove the tests' inclusion in the plugin

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

This PR removes the inclusion of the test as a dependency for the plugin and also changes the composer.json to map and autoload the test only in dev mode.

**Context**
We removed the addition of test files in a production plugin in #76, which generated problems because the test module was included in class-openedx-commerce.php. Problem: https://github.com/openedx/openedx-wordpress-ecommerce/issues/62#issuecomment-2189445156

## Testing instructions

1. Download this plugin with these changes: [ZIP version](https://github.com/eduNEXT/openedx-wordpress-ecommerce/releases/download/v2.0.3/openedx-commerce.zip), that was generated by [this workflow](https://github.com/eduNEXT/openedx-wordpress-ecommerce/actions/runs/9670176669).

2. Install and activate the plugin in a clean WordPress instance (E. g., You can use [Docker](https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/wordpress/) or [Local](https://localwp.com/))

If you want to go further, you can [configure the plugin](https://docs.openedx.org/projects/wordpress-ecommerce-plugin/en/latest/plugin_quickstart.html#configure-the-plugin) and test other functions.

## Additional information

The URL of the zip file I created for testing this PR has the tag v2.0.3, but it is irrelevant because the workflow uploads the zip file in the latest release of my repo which is using this updated branch.
[Ref](https://github.com/eduNEXT/openedx-wordpress-ecommerce/actions/runs/9670176669)

### Video demo (Using Local)
Installing and activating the plugin in a clean installation
https://github.com/openedx/openedx-wordpress-ecommerce/assets/35668326/e9fb881a-8095-473e-a6b4-6ce1a2acc3bb

## Checklist for Merge

- [x] Tested in a remote environment (clean and existent env)
- [x] Rebased master/main
- [x] Squashed commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @MaferMazu! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by felipemontoya — APPROVED** [review]
The changes look correct to me. Is what I would expect to solve the reported issue.

I downloaded the linked plugin package and it installs succesfully.

**Comment by MaferMazu** [comment]
I'll merge this and run the action to generate the ZIP in release 2.0.4 (because the first one wasn't working correctly for the issue this PR is solving).

**Comment by openedx-webhooks** [comment]
@MaferMazu 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-wordpress-ecommerce&entry.867055334=https://github.com/openedx/openedx-wordpress-ecommerce/pull/82&entry.1484655318=https://github.com/MaferMazu&entry.752974735=2024-06-25+21:10&entry.1917517419=2024-06-26+17:29&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
