### PR TITLE
fix: file and class names corrected based on wordpress requirements

### PR DESCRIPTION
**Pull request by julianramirez2**
## Description

The file names were changed due to WordPress restrictions when uploading the plugin, which prohibited the use of reserved words such as 'plugin' or 'woocommerce.' It was decided that this name change would be made to 'openedx_ecommerce' instead of 'openedx_woocommerce_plugin.' Similarly, in accordance with WordPress code best practices, the names of the classes and namespaces used in the code were also changed.

## Testing instructions

Pull the branch locally and run the 'composer install' command to install all plugin dependencies and test. Additionally, these changes have already been uploaded to the staging environment where you can verify that everything is functioning correctly.

## Checklist for Merge

- [X] Tested in a remote environment
- [x] Updated documentation / NA
- [x] Rebased master/main / NA
- [ ] Squashed commits / NA

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @julianramirez2!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by julianramirez2** [comment]
> Hi @julianramirez2! Thanks for this contribution! Please let me know if you have any questions regarding filling out the [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base). If you are submitting on behalf of an organization, please have your manager reach out to [oscm@axim.org](mailto:oscm@axim.org) in order to be added to your organization's entity agreement.

Hi @mphilbrick211, thank you for providing the information. I have just completed the CLA form and am now awaiting the email confirmation of my CLA approval.

**Review by MaferMazu — APPROVED** [review]
This comes because we needed to change the plugin name to submit to the WordPress org, and we want to maintain the congruency of the names.
I was a little afraid because this could generate breaks, but I already tested in stage, and this doesn't break anything.

**Comment by MaferMazu** [comment]
We can't use Woocommerce or Plugin in the name of a WordPress plugin. Is it okay to stay with `openedx-ecommerce`, or is it better to change it to `openedx-commerce`, @feanil?

**Comment by feanil** [comment]
Let's go with `openedx-commerce`

**Comment by feanil** [comment]
Also, can we add an ADR or something about this so we have a record of what the restrictions were when we set the name?

**Comment by MaferMazu** [comment]
@julianramirez2, can you help me with the naming and update #54? I can create the ADR for this.

**Comment by mphilbrick211** [comment]
H @julianramirez2! It looks like your CLA check is still failing. You mentioned you submitted your CLA form last week, but if you are contributing on behalf of eduNEXT, you'll need to have your manager reach out to oscm@axim.org to be added to eduNEXT's entity agreement (if they haven't done so already).

If this has already been done, please let me know and I can check on the status for you. Thanks!

**Review by julianramirez2 — COMMENTED** [review]
Everything looks good

**Comment by mphilbrick211** [comment]
@julianramirez2 great! It looks like a few conflicts popped up - would you mind taking a look?

**Comment by MaferMazu** [comment]
This change is working well
image
And we already changed the name to commerce and added the ADR; what do you think, @feanil?

**Review by MaferMazu — APPROVED** [review]

**Review by felipemontoya — DISMISSED** [review]
Good work @MaferMazu, with the successful test of the code correctly loading and working I think this is good to merge.

**Review by MaferMazu — APPROVED** [review]
I rebase this and It is working well
image

Tested:
- In new instalation
- Stage
- And with Olive and Quince

**Review by feanil — APPROVED** [review]
Name change looks good to me.

**Comment by openedx-webhooks** [comment]
@julianramirez2 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-wordpress-ecommerce&entry.867055334=https://github.com/openedx/openedx-wordpress-ecommerce/pull/53&entry.1484655318=https://github.com/julianramirez2&entry.752974735=2023-10-18+22:27&entry.1917517419=2023-11-09+15:28&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
